### ISSUE TITLE
Lack of byte[] support

### ISSUE THREAD

**Issue by nikitaKlymchukGunnebo** [vitalii-vov/Maui.PDFView#8]
You can load pdf only from uri, but there are cases when your pdf is being downloaded from cloud, and you want to make some processing for it before displaying. This means that in the end you have a byte array that you want to display, and, most likely you don't want to save it to file.

**Comment by vitalii-vov** [comment]
Here a lot depends on what components are used on the platform side.
For example, for Windows and Android, [PdfDocument](https://learn.microsoft.com/en-us/uwp/api/windows.data.pdf.pdfdocument?view=winrt-26100) and [PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) are used, which are created with a constructor and a parameter pointing to a file.

To implement what you want, you will have to save to a file on the rendering side of the platform, which I think is bad, because it is better to control the work with files on the client side.

You can look at the [sample](https://github.com/vitalii-vov/Maui.PDFView/blob/df8d52f4a0e6e07c63530de0882f98db0c439a0c/Example/Business/Services/RepositoryService.cs#L10) code and make your own service for this task.

**Comment by vitalii-vov** [comment]
@nikitaKlymchukGunnebo 
In version 1.5.0 new classes were added that help to work with byte arrays. If this is still relevant, you can use the code like this:
```C#
var bytes =  <your byte array>;
var source = new ByteArrayPdfDataSource(bytes);
PdfSource = await source.GetFilePathAsync();
```
